[package]
name = "ebpf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", package = "aya-ebpf" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", package = "aya-log-ebpf" }
